q=int(input("enter the prime number"))
x=int(input("enter the primitive root for q"))
a=int(input("enter the private key of m"))
b=int(input("enter the private key of n"))
s=int(pow(x,a,q))
t=int(pow(x,b,q))
ka=int(pow(t,a,q))
kb=int(pow(s,b,q))
print("secret key:",ka)
print("secret key:",kb)
